source:
    # twitter:
    #     consumer_key: '[CONSUMER KEY]'
    #     consumer_secret: '[CONSUMER SECRET]'
    #     access_token: '[ACCESS TOKEN]'
    #     access_token_secret: '[ACCESS TOKEN SECRET]'
    hackernews:
        interval: 300
    theverge:
        interval: 300
